name: Doall
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get install --yes gcc ruby

    - name: Compile GUI Backend Server
      run: cd gui_backend_server && gcc gui_backend_server.c -o ../bundle/gui_backend_server

    - name: Zip up files
      run: tar -czf bundle.tar.gz ./bundle

    - name: Package files into unified binary source
      run: ruby scripts/package_files_into_c_src.rb

    - name: Compile unified binary
      run: cd self_extractor && gcc bundle.c self_extractor.c

    - name: Upload binary
      run: |
        aws s3 cp self_extractor/a.out s3://garchinstall/${{ github.sha }} --endpoint=https://garchinstall.sfo3.digitaloceanspaces.com
        aws s3 cp self_extractor/a.out s3://garchinstall/latest --endpoint=https://garchinstall.sfo3.digitaloceanspaces.com --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DIGITALOCEAN_UPLOAD_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DIGITALOCEAN_UPLOAD_KEY_SECRET }}
        AWS_REGION: us-west-1
