name: Doall
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get install --yes gcc
    - name: Compile
      run: gcc cursor.c font.c arch_logo.c keycode_names.c main.c
    - name: Upload binary
      run: |
        aws s3 cp a.out s3://garchinstall/${{ github.sha }} --endpoint=https://garchinstall.sfo3.digitaloceanspaces.com
        aws s3 cp a.out s3://garchinstall/latest --endpoint=https://garchinstall.sfo3.digitaloceanspaces.com --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DIGITALOCEAN_UPLOAD_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DIGITALOCEAN_UPLOAD_KEY_SECRET }}
        AWS_REGION: us-west-1
